### ISSUE TITLE
Error during indexing: Error: ENOENT: no such file or directory, scandir 'z:\'

### ISSUE THREAD

**Issue by soderlundf** [soderlundf/gallery#25]
# OS info

```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

# Environment

## Source or Docker image?

* Docker image `docker pull soderlundf/gallery` 

## Version

* `docker pull soderlundf/gallery:indexer-v0.0.3`

# Actual result/Error

Seen when running `docker logs gallery-indexer`

```
[2024-09-22T18:00:00.556] [ERROR] [node:fs:1502] - Error during indexing: Error: ENOENT: no such file or directory, scandir 'z:\'
    at Object.readdirSync (node:fs:1502:26)
    at indexer.searchFiles (/indexer/indexer/indexer.js:95:20)
    at indexer.indexFiles (/indexer/indexer/indexer.js:54:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async jobs.start_scheduled_job [as _execution] (/indexer/jobs/jobs.js:30:22) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'z:\\'
}
```

# Expected result

It should not produce such an error. Evidently `z:\` is a remnant of development and should be updated to point to the correct path.

**Comment by soderlundf** [comment]
Potential fix implemented in bcf2d9737dff1936e1daeb44fb3ca0fb4e3884ca

Needs testing.
