### ISSUE TITLE
Error: '0 is a invalid expression for second

### ISSUE THREAD

**Issue by soderlundf** [soderlundf/gallery#29]
# OS info

```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

# Environment

## Source or Docker image?

* Docker image `docker pull soderlundf/gallery` 

## Version

* `docker pull soderlundf/gallery:indexer-v0.0.3`

# Actual result/Error

```bash
docker compose -f compose.yaml up
[+] Building 0.1s (10/10) FINISHED                                                                                                                              docker:default
 => [gallery-indexer internal] load build definition from Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 267B                                                                                                                                      0.0s
 => [gallery-indexer internal] load metadata for docker.io/library/node:current-alpine@sha256:c9bb43423a6229aeddf3d16ae6aaa0ff71a0b2951ce18ec8fedb6f5d766cf286            0.0s
 => [gallery-indexer internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                           0.0s
 => [gallery-indexer internal] load build context                                                                                                                         0.0s
 => => transferring context: 633B                                                                                                                                         0.0s
 => [gallery-indexer 1/5] FROM docker.io/library/node:current-alpine@sha256:c9bb43423a6229aeddf3d16ae6aaa0ff71a0b2951ce18ec8fedb6f5d766cf286                              0.0s
 => CACHED [gallery-indexer 2/5] WORKDIR /indexer                                                                                                                         0.0s
 => CACHED [gallery-indexer 3/5] COPY . .                                                                                                                                 0.0s
 => CACHED [gallery-indexer 4/5] RUN mkdir /source_files                                                                                                                  0.0s
 => CACHED [gallery-indexer 5/5] RUN yarn install --production                                                                                                            0.0s
 => [gallery-indexer] exporting to image                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                   0.0s
 => => writing image sha256:329547c4bfb30d16c9c479a721b8a8af0732811035bdbc756fbe2115277116c0                                                                              0.0s
 => => naming to docker.io/library/indexer-gallery-indexer                                                                                                                0.0s
[+] Running 1/1
 ✔ Container gallery-indexer  Created                                                                                                                                     0.1s
Attaching to gallery-indexer
gallery-indexer  | /indexer/node_modules/node-cron/src/pattern-validation.js:86
gallery-indexer  |         throw new Error(`${patterns[0]} is a invalid expression for second`);
gallery-indexer  |         ^
gallery-indexer  |
gallery-indexer  | Error: '0 is a invalid expression for second
gallery-indexer  |     at validateFields (/indexer/node_modules/node-cron/src/pattern-validation.js:86:15)
gallery-indexer  |     at validate (/indexer/node_modules/node-cron/src/pattern-validation.js:121:5)
gallery-indexer  |     at new TimeMatcher (/indexer/node_modules/node-cron/src/time-matcher.js:14:9)
gallery-indexer  |     at new Scheduler (/indexer/node_modules/node-cron/src/scheduler.js:9:28)
gallery-indexer  |     at new ScheduledTask (/indexer/node_modules/node-cron/src/scheduled-task.js:22:27)
gallery-indexer  |     at createTask (/indexer/node_modules/node-cron/src/node-cron.js:36:12)
gallery-indexer  |     at Object.schedule (/indexer/node_modules/node-cron/src/node-cron.js:25:18)
gallery-indexer  |     at Object.<anonymous> (/indexer/jobs/jobs.js:52:6)
gallery-indexer  |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
gallery-indexer  |     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
gallery-indexer  |
gallery-indexer  | Node.js v22.9.0
gallery-indexer exited with code 1
```

**Comment by soderlundf** [comment]
Fixed in 9b08615a6f6e560e29809cc0608cf788b8d19faf
